### ISSUE TITLE
Music stops playing after picking up any item at any level

### ISSUE THREAD

**Issue by paivaleonardo** [ArcadeTV/msu-md-mw4#1]
Patch version: v.0.1, soundPack_MW4_swineIsOnline_AOST.bin

Platform: RetroArch GenesisPlusGX 58758ae

The music stops playing after picking up an item at any level.

**Comment by ArcadeTV** [comment]
Thanks for testing!
I will re-route the item-get-jingles to chipsounds.

**Comment by ArcadeTV** [comment]
Fixed in v0.2:
https://github.com/ArcadeTV/msu-md-mw4/releases/tag/v0.2

**Comment by ArcadeTV** [comment]
ps. the soundPack has changed!

**Comment by paivaleonardo** [comment]
Its Ok now.
