### ISSUE TITLE
[real MD] Save Feature doesn't work

### ISSUE THREAD

**Issue by Agentmanbh** [ArcadeTV/msu-md-mw4#2]
**Patch version**
MW4_MSU-MD_v0.2_ArcadeTV

**Platform**
MEGA ED PRO on real hardware

**Describe the bug**
After applying patch, game don't save progress.

**Additional context**
Clean source ROM was tested too and save feature works fine.

**Comment by skins4thewin** [comment]
I am having the exact same issue using the Analogue Mega SG.  ROM file saves fine without the MSU-MD patch but once patched it will not save.  After saving in game the save file slot remains blank and the Mega ED Pro does not write a save file to the SD card.  I assume this must be a systemic problem considering this is also happening on real hardware.  This is a pretty major bug & makes the game rather unplayable, how come this issue hasn't been addressed yet?

**Comment by ArcadeTV** [comment]
fixed in v0.3
